### PR TITLE
Add support for arrays of links

### PR DESCRIPTION
**Pull request by davestewart**
As-per #32, I looked to add support for arrays of links.

This seems to work for me on real world URLs.

### CODE REVIEW

**Comment by deblockt** [comment]
can you add information on the README to document this enhancement

**Comment by davestewart** [comment]
Oh crap I missed an `await` here:

- https://github.com/deblockt/hal-rest-client/pull/33/commits/0eaf6e4fceec636daec1e762bd5f00f3107cfb82#diff-04c6e90faac2675aa89e2176d2eec7d8R107

Want me to update that now?

**Comment by davestewart** [comment]
Don't forget to publish to NPM !

**Comment by deblockt** [comment]
travis should do that... But it failed because npm has changed :'(
I have no time to look at this now...

**Comment by davestewart** [comment]
`npm publish` in the terminal should do the trick!

**Comment by deblockt** [comment]
this release has been published

**Pull request merged**
